### ISSUE TITLE
Cannot even test the mod : it crashs !

### ISSUE THREAD

**Issue by ExDomino** [Fexcraft/FVTM#22] opened 2018-09-13 04:45 UTC
The mod crashs, I'm using the latest fixedversion downloaded here:
https://github.com/Fexcraft/FVTM/issues/21

Cannot spawn any vehicle because the creative tab makes the game crashing.

java.lang.NullPointerException: Rendering item
	at net.fexcraft.mod.fvtm.model.vehicle.VehicleBaseModel.lambda$renderItem$7(VehicleBaseModel.java:100)
	at java.util.TreeMap.forEach(Unknown Source)
	at net.fexcraft.mod.fvtm.model.vehicle.VehicleBaseModel.renderItem(VehicleBaseModel.java:97)
	at net.fexcraft.mod.lib.fmr.FCLItemModelLoader$BakedModel.handlePerspective(FCLItemModelLoader.java:132)
	at net.minecraftforge.client.ForgeHooksClient.handleCameraTransforms(ForgeHooksClient.java:412)
	at net.minecraft.client.renderer.RenderItem.func_191962_a(RenderItem.java:302)
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:342)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:265)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:98)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:643)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:381)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Fexcraft** [comment] 2018-09-13 07:24
Could you give the rest of the log, or the versions of fcl, fvtm & the packs you have installed?
(the log lists the installed addons / versions)

**Comment by ExDomino** [comment] 2018-09-13 07:27
All latest for forge 1.12.2 installed tonight, few minutes before reporting the bug.

**Comment by Fexcraft** [comment] 2018-09-13 07:28
I'd still need the versions, or the log as it may be faster.
The errors seems to be caused by a missing part model, which usually shouldn't happen at that point, except e.g. a pack is outdated and as such models fail to load.

**Comment by ExDomino** [comment] 2018-09-13 07:29
It's a pack made by me. I told you, all the versions I used are latest vesions donwloaded 2 hours ago from here. I used all of yours mods.

**Comment by Fexcraft** [comment] 2018-09-13 07:34
Look, a crash log has that data at end, I need the versions off FCL, FVTM and any addon pack, I had a lot of times people ending up to use the wrong version.
![image](https://user-images.githubusercontent.com/11726534/45473663-ef428b00-b737-11e8-98f5-59d8b71b161b.png)
And until I'm sure the addons are alright I cannot check other code, as the place where the crash happens, parts which have no model configured would load a placeholder, so currently only thing that could crash is a part which has a model configured but failed to load.

**Comment by ExDomino** [comment] 2018-09-13 07:37
I will test again if you want but I have to re-install your mods again.

**Comment by Fexcraft** [comment] 2018-09-30 20:16
Should be fixed in 2.8.33

**Closed as completed by Fexcraft** 2018-09-30 20:16 UTC
